/* eslint-disable */
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /**
   * Define a Relay Cursor type:
   * https://relay.dev/graphql/connections.htm#sec-Cursor
   */
  Cursor: { input: any; output: any; }
};

export type Bank = Node & {
  __typename?: 'Bank';
  country: Scalars['String']['output'];
  currencyRates?: Maybe<Array<CurrencyRate>>;
  id: Scalars['ID']['output'];
  logoURL?: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  offers?: Maybe<Array<Offer>>;
  website?: Maybe<Scalars['String']['output']>;
};

/** A connection to a list of items. */
export type BankConnection = {
  __typename?: 'BankConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<BankEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type BankEdge = {
  __typename?: 'BankEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Bank>;
};

/**
 * BankWhereInput is used for filtering Bank objects.
 * Input was generated by ent.
 */
export type BankWhereInput = {
  and?: InputMaybe<Array<BankWhereInput>>;
  /** country field predicates */
  country?: InputMaybe<Scalars['String']['input']>;
  countryContains?: InputMaybe<Scalars['String']['input']>;
  countryContainsFold?: InputMaybe<Scalars['String']['input']>;
  countryEqualFold?: InputMaybe<Scalars['String']['input']>;
  countryGT?: InputMaybe<Scalars['String']['input']>;
  countryGTE?: InputMaybe<Scalars['String']['input']>;
  countryHasPrefix?: InputMaybe<Scalars['String']['input']>;
  countryHasSuffix?: InputMaybe<Scalars['String']['input']>;
  countryIn?: InputMaybe<Array<Scalars['String']['input']>>;
  countryLT?: InputMaybe<Scalars['String']['input']>;
  countryLTE?: InputMaybe<Scalars['String']['input']>;
  countryNEQ?: InputMaybe<Scalars['String']['input']>;
  countryNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** currency_rates edge predicates */
  hasCurrencyRates?: InputMaybe<Scalars['Boolean']['input']>;
  hasCurrencyRatesWith?: InputMaybe<Array<CurrencyRateWhereInput>>;
  /** offers edge predicates */
  hasOffers?: InputMaybe<Scalars['Boolean']['input']>;
  hasOffersWith?: InputMaybe<Array<OfferWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** logo_url field predicates */
  logoURL?: InputMaybe<Scalars['String']['input']>;
  logoURLContains?: InputMaybe<Scalars['String']['input']>;
  logoURLContainsFold?: InputMaybe<Scalars['String']['input']>;
  logoURLEqualFold?: InputMaybe<Scalars['String']['input']>;
  logoURLGT?: InputMaybe<Scalars['String']['input']>;
  logoURLGTE?: InputMaybe<Scalars['String']['input']>;
  logoURLHasPrefix?: InputMaybe<Scalars['String']['input']>;
  logoURLHasSuffix?: InputMaybe<Scalars['String']['input']>;
  logoURLIn?: InputMaybe<Array<Scalars['String']['input']>>;
  logoURLIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  logoURLLT?: InputMaybe<Scalars['String']['input']>;
  logoURLLTE?: InputMaybe<Scalars['String']['input']>;
  logoURLNEQ?: InputMaybe<Scalars['String']['input']>;
  logoURLNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  logoURLNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<BankWhereInput>;
  or?: InputMaybe<Array<BankWhereInput>>;
  /** website field predicates */
  website?: InputMaybe<Scalars['String']['input']>;
  websiteContains?: InputMaybe<Scalars['String']['input']>;
  websiteContainsFold?: InputMaybe<Scalars['String']['input']>;
  websiteEqualFold?: InputMaybe<Scalars['String']['input']>;
  websiteGT?: InputMaybe<Scalars['String']['input']>;
  websiteGTE?: InputMaybe<Scalars['String']['input']>;
  websiteHasPrefix?: InputMaybe<Scalars['String']['input']>;
  websiteHasSuffix?: InputMaybe<Scalars['String']['input']>;
  websiteIn?: InputMaybe<Array<Scalars['String']['input']>>;
  websiteIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  websiteLT?: InputMaybe<Scalars['String']['input']>;
  websiteLTE?: InputMaybe<Scalars['String']['input']>;
  websiteNEQ?: InputMaybe<Scalars['String']['input']>;
  websiteNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  websiteNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

/**
 * CreateBankInput is used for create Bank object.
 * Input was generated by ent.
 */
export type CreateBankInput = {
  country: Scalars['String']['input'];
  currencyRateIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  logoURL?: InputMaybe<Scalars['String']['input']>;
  name: Scalars['String']['input'];
  offerIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  website?: InputMaybe<Scalars['String']['input']>;
};

/**
 * CreateCurrencyRateInput is used for create CurrencyRate object.
 * Input was generated by ent.
 */
export type CreateCurrencyRateInput = {
  bankID: Scalars['ID']['input'];
  /** ISO 4217 currency code */
  currency: Scalars['String']['input'];
  rate: Scalars['Float']['input'];
};

/**
 * CreateOfferInput is used for create Offer object.
 * Input was generated by ent.
 */
export type CreateOfferInput = {
  bankID: Scalars['ID']['input'];
  description: Scalars['String']['input'];
  link: Scalars['String']['input'];
  type: Scalars['String']['input'];
};

export type CurrencyRate = Node & {
  __typename?: 'CurrencyRate';
  bank: Bank;
  /** ISO 4217 currency code */
  currency: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  rate: Scalars['Float']['output'];
};

/**
 * CurrencyRateWhereInput is used for filtering CurrencyRate objects.
 * Input was generated by ent.
 */
export type CurrencyRateWhereInput = {
  and?: InputMaybe<Array<CurrencyRateWhereInput>>;
  /** currency field predicates */
  currency?: InputMaybe<Scalars['String']['input']>;
  currencyContains?: InputMaybe<Scalars['String']['input']>;
  currencyContainsFold?: InputMaybe<Scalars['String']['input']>;
  currencyEqualFold?: InputMaybe<Scalars['String']['input']>;
  currencyGT?: InputMaybe<Scalars['String']['input']>;
  currencyGTE?: InputMaybe<Scalars['String']['input']>;
  currencyHasPrefix?: InputMaybe<Scalars['String']['input']>;
  currencyHasSuffix?: InputMaybe<Scalars['String']['input']>;
  currencyIn?: InputMaybe<Array<Scalars['String']['input']>>;
  currencyLT?: InputMaybe<Scalars['String']['input']>;
  currencyLTE?: InputMaybe<Scalars['String']['input']>;
  currencyNEQ?: InputMaybe<Scalars['String']['input']>;
  currencyNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** bank edge predicates */
  hasBank?: InputMaybe<Scalars['Boolean']['input']>;
  hasBankWith?: InputMaybe<Array<BankWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<CurrencyRateWhereInput>;
  or?: InputMaybe<Array<CurrencyRateWhereInput>>;
  /** rate field predicates */
  rate?: InputMaybe<Scalars['Float']['input']>;
  rateGT?: InputMaybe<Scalars['Float']['input']>;
  rateGTE?: InputMaybe<Scalars['Float']['input']>;
  rateIn?: InputMaybe<Array<Scalars['Float']['input']>>;
  rateLT?: InputMaybe<Scalars['Float']['input']>;
  rateLTE?: InputMaybe<Scalars['Float']['input']>;
  rateNEQ?: InputMaybe<Scalars['Float']['input']>;
  rateNotIn?: InputMaybe<Array<Scalars['Float']['input']>>;
};

/**
 * An object with an ID.
 * Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)
 */
export type Node = {
  /** The id of the object. */
  id: Scalars['ID']['output'];
};

export type Offer = Node & {
  __typename?: 'Offer';
  bank: Bank;
  description: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  link: Scalars['String']['output'];
  type: Scalars['String']['output'];
};

/**
 * OfferWhereInput is used for filtering Offer objects.
 * Input was generated by ent.
 */
export type OfferWhereInput = {
  and?: InputMaybe<Array<OfferWhereInput>>;
  /** description field predicates */
  description?: InputMaybe<Scalars['String']['input']>;
  descriptionContains?: InputMaybe<Scalars['String']['input']>;
  descriptionContainsFold?: InputMaybe<Scalars['String']['input']>;
  descriptionEqualFold?: InputMaybe<Scalars['String']['input']>;
  descriptionGT?: InputMaybe<Scalars['String']['input']>;
  descriptionGTE?: InputMaybe<Scalars['String']['input']>;
  descriptionHasPrefix?: InputMaybe<Scalars['String']['input']>;
  descriptionHasSuffix?: InputMaybe<Scalars['String']['input']>;
  descriptionIn?: InputMaybe<Array<Scalars['String']['input']>>;
  descriptionLT?: InputMaybe<Scalars['String']['input']>;
  descriptionLTE?: InputMaybe<Scalars['String']['input']>;
  descriptionNEQ?: InputMaybe<Scalars['String']['input']>;
  descriptionNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** bank edge predicates */
  hasBank?: InputMaybe<Scalars['Boolean']['input']>;
  hasBankWith?: InputMaybe<Array<BankWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** link field predicates */
  link?: InputMaybe<Scalars['String']['input']>;
  linkContains?: InputMaybe<Scalars['String']['input']>;
  linkContainsFold?: InputMaybe<Scalars['String']['input']>;
  linkEqualFold?: InputMaybe<Scalars['String']['input']>;
  linkGT?: InputMaybe<Scalars['String']['input']>;
  linkGTE?: InputMaybe<Scalars['String']['input']>;
  linkHasPrefix?: InputMaybe<Scalars['String']['input']>;
  linkHasSuffix?: InputMaybe<Scalars['String']['input']>;
  linkIn?: InputMaybe<Array<Scalars['String']['input']>>;
  linkLT?: InputMaybe<Scalars['String']['input']>;
  linkLTE?: InputMaybe<Scalars['String']['input']>;
  linkNEQ?: InputMaybe<Scalars['String']['input']>;
  linkNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<OfferWhereInput>;
  or?: InputMaybe<Array<OfferWhereInput>>;
  /** type field predicates */
  type?: InputMaybe<Scalars['String']['input']>;
  typeContains?: InputMaybe<Scalars['String']['input']>;
  typeContainsFold?: InputMaybe<Scalars['String']['input']>;
  typeEqualFold?: InputMaybe<Scalars['String']['input']>;
  typeGT?: InputMaybe<Scalars['String']['input']>;
  typeGTE?: InputMaybe<Scalars['String']['input']>;
  typeHasPrefix?: InputMaybe<Scalars['String']['input']>;
  typeHasSuffix?: InputMaybe<Scalars['String']['input']>;
  typeIn?: InputMaybe<Array<Scalars['String']['input']>>;
  typeLT?: InputMaybe<Scalars['String']['input']>;
  typeLTE?: InputMaybe<Scalars['String']['input']>;
  typeNEQ?: InputMaybe<Scalars['String']['input']>;
  typeNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
};

/** Possible directions in which to order a list of items when provided an `orderBy` argument. */
export enum OrderDirection {
  /** Specifies an ascending order for a given `orderBy` argument. */
  Asc = 'ASC',
  /** Specifies a descending order for a given `orderBy` argument. */
  Desc = 'DESC'
}

/**
 * Information about pagination in a connection.
 * https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo
 */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['Cursor']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['Cursor']['output']>;
};

export type Query = {
  __typename?: 'Query';
  bank?: Maybe<Bank>;
  banks: BankConnection;
  currencyRates: Array<CurrencyRate>;
  /** Fetches an object given its ID. */
  node?: Maybe<Node>;
  /** Lookup nodes by a list of IDs. */
  nodes: Array<Maybe<Node>>;
  offers: Array<Offer>;
};


export type QueryBankArgs = {
  id: Scalars['ID']['input'];
};


export type QueryBanksArgs = {
  after?: InputMaybe<Scalars['Cursor']['input']>;
  before?: InputMaybe<Scalars['Cursor']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<BankWhereInput>;
};


export type QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type QueryNodesArgs = {
  ids: Array<Scalars['ID']['input']>;
};

/**
 * UpdateBankInput is used for update Bank object.
 * Input was generated by ent.
 */
export type UpdateBankInput = {
  addCurrencyRateIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  addOfferIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  clearCurrencyRates?: InputMaybe<Scalars['Boolean']['input']>;
  clearLogoURL?: InputMaybe<Scalars['Boolean']['input']>;
  clearOffers?: InputMaybe<Scalars['Boolean']['input']>;
  clearWebsite?: InputMaybe<Scalars['Boolean']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
  logoURL?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  removeCurrencyRateIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  removeOfferIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  website?: InputMaybe<Scalars['String']['input']>;
};

/**
 * UpdateCurrencyRateInput is used for update CurrencyRate object.
 * Input was generated by ent.
 */
export type UpdateCurrencyRateInput = {
  bankID?: InputMaybe<Scalars['ID']['input']>;
  /** ISO 4217 currency code */
  currency?: InputMaybe<Scalars['String']['input']>;
  rate?: InputMaybe<Scalars['Float']['input']>;
};

/**
 * UpdateOfferInput is used for update Offer object.
 * Input was generated by ent.
 */
export type UpdateOfferInput = {
  bankID?: InputMaybe<Scalars['ID']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
};

export type GetBankQueryVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type GetBankQuery = { __typename?: 'Query', bank?: { __typename?: 'Bank', id: string, name: string, country: string, logoURL?: string | null, website?: string | null, currencyRates?: Array<{ __typename?: 'CurrencyRate', id: string, currency: string, rate: number }> | null, offers?: Array<{ __typename?: 'Offer', id: string, description: string, link: string, type: string }> | null } | null };

export type GetBanksQueryVariables = Exact<{ [key: string]: never; }>;


export type GetBanksQuery = { __typename?: 'Query', banks: { __typename?: 'BankConnection', edges?: Array<{ __typename?: 'BankEdge', node?: { __typename?: 'Bank', id: string, name: string, country: string, logoURL?: string | null, website?: string | null, currencyRates?: Array<{ __typename?: 'CurrencyRate', id: string, currency: string, rate: number }> | null, offers?: Array<{ __typename?: 'Offer', id: string, description: string, link: string, type: string }> | null } | null } | null> | null } };


export const GetBankDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetBank"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"bank"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"country"}},{"kind":"Field","name":{"kind":"Name","value":"logoURL"}},{"kind":"Field","name":{"kind":"Name","value":"currencyRates"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"currency"}},{"kind":"Field","name":{"kind":"Name","value":"rate"}}]}},{"kind":"Field","name":{"kind":"Name","value":"website"}},{"kind":"Field","name":{"kind":"Name","value":"offers"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"link"}},{"kind":"Field","name":{"kind":"Name","value":"type"}}]}}]}}]}}]} as unknown as DocumentNode<GetBankQuery, GetBankQueryVariables>;
export const GetBanksDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetBanks"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"banks"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"edges"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"node"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"country"}},{"kind":"Field","name":{"kind":"Name","value":"logoURL"}},{"kind":"Field","name":{"kind":"Name","value":"currencyRates"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"currency"}},{"kind":"Field","name":{"kind":"Name","value":"rate"}}]}},{"kind":"Field","name":{"kind":"Name","value":"website"}},{"kind":"Field","name":{"kind":"Name","value":"offers"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"link"}},{"kind":"Field","name":{"kind":"Name","value":"type"}}]}}]}}]}}]}}]}}]} as unknown as DocumentNode<GetBanksQuery, GetBanksQueryVariables>;