openapi: 3.0.0
info:
  title: Bank Directory API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3001/api/v1
    description: Локальный сервер (по умолчанию)
paths:
  /banks:
    get:
      summary: Получить список банков
      responses:
        "200":
          description: Список банков
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Bank"
  /banks/{id}:
    get:
      summary: Получить банк по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Данные о банке
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bank"

components:
  schemas:
    Bank:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        country:
          type: string
        website:
          type: string
        logoUrl:
          type: string
        currencyRates:
          type: array
          items:
            $ref: "#/components/schemas/CurrencyRate"
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"
        updatedAt:
          type: string
          format: date-time

    CurrencyRate:
      type: object
      properties:
        currency:
          $ref: "#/components/schemas/CurrencyCode"
        rate:
          type: number

    Offer:
      type: object
      properties:
        type:
          type: string
        description:
          type: string
        link:
          type: string

    CurrencyCode:
      type: string
      enum:
        - USD
        - EUR
        - GBP
        - JPY
        - CHF
        - CAD
        - AUD
        - CNY
        - RUB
        - UAH
      description: "Коды валют в формате ISO 4217"
