/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BankCreate } from '../models';
// @ts-ignore
import type { BankCurrencyRatesList } from '../models';
// @ts-ignore
import type { BankList } from '../models';
// @ts-ignore
import type { BankOffersList } from '../models';
// @ts-ignore
import type { BankRead } from '../models';
// @ts-ignore
import type { BankUpdate } from '../models';
// @ts-ignore
import type { CreateBankRequest } from '../models';
// @ts-ignore
import type { ListBank400Response } from '../models';
// @ts-ignore
import type { UpdateBankRequest } from '../models';
/**
 * BankApi - axios parameter creator
 * @export
 */
export const BankApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new Bank and persists it to storage.
         * @summary Create a new Bank
         * @param {CreateBankRequest} createBankRequest Bank to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBank: async (createBankRequest: CreateBankRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createBankRequest' is not null or undefined
            assertParamExists('createBank', 'createBankRequest', createBankRequest)
            const localVarPath = `/banks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBankRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes the Bank with the requested ID.
         * @summary Deletes a Bank by ID
         * @param {number} id ID of the Bank
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBank: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteBank', 'id', id)
            const localVarPath = `/banks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List Banks.
         * @summary List Banks
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBank: async (page?: number, itemsPerPage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/banks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List attached CurrencyRates.
         * @summary List attached CurrencyRates
         * @param {number} id ID of the Bank
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBankCurrencyRates: async (id: number, page?: number, itemsPerPage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listBankCurrencyRates', 'id', id)
            const localVarPath = `/banks/{id}/currency-rates`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List attached Offers.
         * @summary List attached Offers
         * @param {number} id ID of the Bank
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBankOffers: async (id: number, page?: number, itemsPerPage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listBankOffers', 'id', id)
            const localVarPath = `/banks/{id}/offers`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Finds the Bank with the requested ID and returns it.
         * @summary Find a Bank by ID
         * @param {number} id ID of the Bank
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readBank: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('readBank', 'id', id)
            const localVarPath = `/banks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a Bank and persists changes to storage.
         * @summary Updates a Bank
         * @param {number} id ID of the Bank
         * @param {UpdateBankRequest} updateBankRequest Bank properties to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBank: async (id: number, updateBankRequest: UpdateBankRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateBank', 'id', id)
            // verify required parameter 'updateBankRequest' is not null or undefined
            assertParamExists('updateBank', 'updateBankRequest', updateBankRequest)
            const localVarPath = `/banks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateBankRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BankApi - functional programming interface
 * @export
 */
export const BankApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BankApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new Bank and persists it to storage.
         * @summary Create a new Bank
         * @param {CreateBankRequest} createBankRequest Bank to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBank(createBankRequest: CreateBankRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BankCreate>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBank(createBankRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BankApi.createBank']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes the Bank with the requested ID.
         * @summary Deletes a Bank by ID
         * @param {number} id ID of the Bank
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBank(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteBank(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BankApi.deleteBank']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List Banks.
         * @summary List Banks
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBank(page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BankList>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBank(page, itemsPerPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BankApi.listBank']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List attached CurrencyRates.
         * @summary List attached CurrencyRates
         * @param {number} id ID of the Bank
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBankCurrencyRates(id: number, page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BankCurrencyRatesList>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBankCurrencyRates(id, page, itemsPerPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BankApi.listBankCurrencyRates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List attached Offers.
         * @summary List attached Offers
         * @param {number} id ID of the Bank
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBankOffers(id: number, page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BankOffersList>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBankOffers(id, page, itemsPerPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BankApi.listBankOffers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Finds the Bank with the requested ID and returns it.
         * @summary Find a Bank by ID
         * @param {number} id ID of the Bank
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readBank(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BankRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readBank(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BankApi.readBank']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates a Bank and persists changes to storage.
         * @summary Updates a Bank
         * @param {number} id ID of the Bank
         * @param {UpdateBankRequest} updateBankRequest Bank properties to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBank(id: number, updateBankRequest: UpdateBankRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BankUpdate>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateBank(id, updateBankRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BankApi.updateBank']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BankApi - factory interface
 * @export
 */
export const BankApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BankApiFp(configuration)
    return {
        /**
         * Creates a new Bank and persists it to storage.
         * @summary Create a new Bank
         * @param {CreateBankRequest} createBankRequest Bank to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBank(createBankRequest: CreateBankRequest, options?: RawAxiosRequestConfig): AxiosPromise<BankCreate> {
            return localVarFp.createBank(createBankRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes the Bank with the requested ID.
         * @summary Deletes a Bank by ID
         * @param {number} id ID of the Bank
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBank(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteBank(id, options).then((request) => request(axios, basePath));
        },
        /**
         * List Banks.
         * @summary List Banks
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBank(page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<BankList>> {
            return localVarFp.listBank(page, itemsPerPage, options).then((request) => request(axios, basePath));
        },
        /**
         * List attached CurrencyRates.
         * @summary List attached CurrencyRates
         * @param {number} id ID of the Bank
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBankCurrencyRates(id: number, page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<BankCurrencyRatesList>> {
            return localVarFp.listBankCurrencyRates(id, page, itemsPerPage, options).then((request) => request(axios, basePath));
        },
        /**
         * List attached Offers.
         * @summary List attached Offers
         * @param {number} id ID of the Bank
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBankOffers(id: number, page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<BankOffersList>> {
            return localVarFp.listBankOffers(id, page, itemsPerPage, options).then((request) => request(axios, basePath));
        },
        /**
         * Finds the Bank with the requested ID and returns it.
         * @summary Find a Bank by ID
         * @param {number} id ID of the Bank
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readBank(id: number, options?: RawAxiosRequestConfig): AxiosPromise<BankRead> {
            return localVarFp.readBank(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a Bank and persists changes to storage.
         * @summary Updates a Bank
         * @param {number} id ID of the Bank
         * @param {UpdateBankRequest} updateBankRequest Bank properties to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBank(id: number, updateBankRequest: UpdateBankRequest, options?: RawAxiosRequestConfig): AxiosPromise<BankUpdate> {
            return localVarFp.updateBank(id, updateBankRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BankApi - object-oriented interface
 * @export
 * @class BankApi
 * @extends {BaseAPI}
 */
export class BankApi extends BaseAPI {
    /**
     * Creates a new Bank and persists it to storage.
     * @summary Create a new Bank
     * @param {CreateBankRequest} createBankRequest Bank to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankApi
     */
    public createBank(createBankRequest: CreateBankRequest, options?: RawAxiosRequestConfig) {
        return BankApiFp(this.configuration).createBank(createBankRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes the Bank with the requested ID.
     * @summary Deletes a Bank by ID
     * @param {number} id ID of the Bank
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankApi
     */
    public deleteBank(id: number, options?: RawAxiosRequestConfig) {
        return BankApiFp(this.configuration).deleteBank(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List Banks.
     * @summary List Banks
     * @param {number} [page] what page to render
     * @param {number} [itemsPerPage] item count to render per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankApi
     */
    public listBank(page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig) {
        return BankApiFp(this.configuration).listBank(page, itemsPerPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List attached CurrencyRates.
     * @summary List attached CurrencyRates
     * @param {number} id ID of the Bank
     * @param {number} [page] what page to render
     * @param {number} [itemsPerPage] item count to render per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankApi
     */
    public listBankCurrencyRates(id: number, page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig) {
        return BankApiFp(this.configuration).listBankCurrencyRates(id, page, itemsPerPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List attached Offers.
     * @summary List attached Offers
     * @param {number} id ID of the Bank
     * @param {number} [page] what page to render
     * @param {number} [itemsPerPage] item count to render per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankApi
     */
    public listBankOffers(id: number, page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig) {
        return BankApiFp(this.configuration).listBankOffers(id, page, itemsPerPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Finds the Bank with the requested ID and returns it.
     * @summary Find a Bank by ID
     * @param {number} id ID of the Bank
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankApi
     */
    public readBank(id: number, options?: RawAxiosRequestConfig) {
        return BankApiFp(this.configuration).readBank(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates a Bank and persists changes to storage.
     * @summary Updates a Bank
     * @param {number} id ID of the Bank
     * @param {UpdateBankRequest} updateBankRequest Bank properties to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BankApi
     */
    public updateBank(id: number, updateBankRequest: UpdateBankRequest, options?: RawAxiosRequestConfig) {
        return BankApiFp(this.configuration).updateBank(id, updateBankRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

