/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateCurrencyRateRequest } from '../models';
// @ts-ignore
import type { CurrencyRateBankRead } from '../models';
// @ts-ignore
import type { CurrencyRateCreate } from '../models';
// @ts-ignore
import type { CurrencyRateList } from '../models';
// @ts-ignore
import type { CurrencyRateRead } from '../models';
// @ts-ignore
import type { CurrencyRateUpdate } from '../models';
// @ts-ignore
import type { ListBank400Response } from '../models';
// @ts-ignore
import type { UpdateCurrencyRateRequest } from '../models';
/**
 * CurrencyRateApi - axios parameter creator
 * @export
 */
export const CurrencyRateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new CurrencyRate and persists it to storage.
         * @summary Create a new CurrencyRate
         * @param {CreateCurrencyRateRequest} createCurrencyRateRequest CurrencyRate to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCurrencyRate: async (createCurrencyRateRequest: CreateCurrencyRateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCurrencyRateRequest' is not null or undefined
            assertParamExists('createCurrencyRate', 'createCurrencyRateRequest', createCurrencyRateRequest)
            const localVarPath = `/currency-rates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCurrencyRateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes the CurrencyRate with the requested ID.
         * @summary Deletes a CurrencyRate by ID
         * @param {number} id ID of the CurrencyRate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCurrencyRate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteCurrencyRate', 'id', id)
            const localVarPath = `/currency-rates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List CurrencyRates.
         * @summary List CurrencyRates
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCurrencyRate: async (page?: number, itemsPerPage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/currency-rates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Finds the CurrencyRate with the requested ID and returns it.
         * @summary Find a CurrencyRate by ID
         * @param {number} id ID of the CurrencyRate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readCurrencyRate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('readCurrencyRate', 'id', id)
            const localVarPath = `/currency-rates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Find the attached Bank of the CurrencyRate with the given ID
         * @summary Find the attached Bank
         * @param {number} id ID of the CurrencyRate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readCurrencyRateBank: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('readCurrencyRateBank', 'id', id)
            const localVarPath = `/currency-rates/{id}/bank`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a CurrencyRate and persists changes to storage.
         * @summary Updates a CurrencyRate
         * @param {number} id ID of the CurrencyRate
         * @param {UpdateCurrencyRateRequest} updateCurrencyRateRequest CurrencyRate properties to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCurrencyRate: async (id: number, updateCurrencyRateRequest: UpdateCurrencyRateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateCurrencyRate', 'id', id)
            // verify required parameter 'updateCurrencyRateRequest' is not null or undefined
            assertParamExists('updateCurrencyRate', 'updateCurrencyRateRequest', updateCurrencyRateRequest)
            const localVarPath = `/currency-rates/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCurrencyRateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CurrencyRateApi - functional programming interface
 * @export
 */
export const CurrencyRateApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CurrencyRateApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new CurrencyRate and persists it to storage.
         * @summary Create a new CurrencyRate
         * @param {CreateCurrencyRateRequest} createCurrencyRateRequest CurrencyRate to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCurrencyRate(createCurrencyRateRequest: CreateCurrencyRateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrencyRateCreate>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCurrencyRate(createCurrencyRateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrencyRateApi.createCurrencyRate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes the CurrencyRate with the requested ID.
         * @summary Deletes a CurrencyRate by ID
         * @param {number} id ID of the CurrencyRate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCurrencyRate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCurrencyRate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrencyRateApi.deleteCurrencyRate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List CurrencyRates.
         * @summary List CurrencyRates
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCurrencyRate(page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CurrencyRateList>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCurrencyRate(page, itemsPerPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrencyRateApi.listCurrencyRate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Finds the CurrencyRate with the requested ID and returns it.
         * @summary Find a CurrencyRate by ID
         * @param {number} id ID of the CurrencyRate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readCurrencyRate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrencyRateRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readCurrencyRate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrencyRateApi.readCurrencyRate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Find the attached Bank of the CurrencyRate with the given ID
         * @summary Find the attached Bank
         * @param {number} id ID of the CurrencyRate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readCurrencyRateBank(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrencyRateBankRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readCurrencyRateBank(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrencyRateApi.readCurrencyRateBank']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates a CurrencyRate and persists changes to storage.
         * @summary Updates a CurrencyRate
         * @param {number} id ID of the CurrencyRate
         * @param {UpdateCurrencyRateRequest} updateCurrencyRateRequest CurrencyRate properties to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCurrencyRate(id: number, updateCurrencyRateRequest: UpdateCurrencyRateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrencyRateUpdate>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCurrencyRate(id, updateCurrencyRateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrencyRateApi.updateCurrencyRate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CurrencyRateApi - factory interface
 * @export
 */
export const CurrencyRateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CurrencyRateApiFp(configuration)
    return {
        /**
         * Creates a new CurrencyRate and persists it to storage.
         * @summary Create a new CurrencyRate
         * @param {CreateCurrencyRateRequest} createCurrencyRateRequest CurrencyRate to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCurrencyRate(createCurrencyRateRequest: CreateCurrencyRateRequest, options?: RawAxiosRequestConfig): AxiosPromise<CurrencyRateCreate> {
            return localVarFp.createCurrencyRate(createCurrencyRateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes the CurrencyRate with the requested ID.
         * @summary Deletes a CurrencyRate by ID
         * @param {number} id ID of the CurrencyRate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCurrencyRate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteCurrencyRate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * List CurrencyRates.
         * @summary List CurrencyRates
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCurrencyRate(page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<CurrencyRateList>> {
            return localVarFp.listCurrencyRate(page, itemsPerPage, options).then((request) => request(axios, basePath));
        },
        /**
         * Finds the CurrencyRate with the requested ID and returns it.
         * @summary Find a CurrencyRate by ID
         * @param {number} id ID of the CurrencyRate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readCurrencyRate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<CurrencyRateRead> {
            return localVarFp.readCurrencyRate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Find the attached Bank of the CurrencyRate with the given ID
         * @summary Find the attached Bank
         * @param {number} id ID of the CurrencyRate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readCurrencyRateBank(id: number, options?: RawAxiosRequestConfig): AxiosPromise<CurrencyRateBankRead> {
            return localVarFp.readCurrencyRateBank(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a CurrencyRate and persists changes to storage.
         * @summary Updates a CurrencyRate
         * @param {number} id ID of the CurrencyRate
         * @param {UpdateCurrencyRateRequest} updateCurrencyRateRequest CurrencyRate properties to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCurrencyRate(id: number, updateCurrencyRateRequest: UpdateCurrencyRateRequest, options?: RawAxiosRequestConfig): AxiosPromise<CurrencyRateUpdate> {
            return localVarFp.updateCurrencyRate(id, updateCurrencyRateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CurrencyRateApi - object-oriented interface
 * @export
 * @class CurrencyRateApi
 * @extends {BaseAPI}
 */
export class CurrencyRateApi extends BaseAPI {
    /**
     * Creates a new CurrencyRate and persists it to storage.
     * @summary Create a new CurrencyRate
     * @param {CreateCurrencyRateRequest} createCurrencyRateRequest CurrencyRate to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyRateApi
     */
    public createCurrencyRate(createCurrencyRateRequest: CreateCurrencyRateRequest, options?: RawAxiosRequestConfig) {
        return CurrencyRateApiFp(this.configuration).createCurrencyRate(createCurrencyRateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes the CurrencyRate with the requested ID.
     * @summary Deletes a CurrencyRate by ID
     * @param {number} id ID of the CurrencyRate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyRateApi
     */
    public deleteCurrencyRate(id: number, options?: RawAxiosRequestConfig) {
        return CurrencyRateApiFp(this.configuration).deleteCurrencyRate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List CurrencyRates.
     * @summary List CurrencyRates
     * @param {number} [page] what page to render
     * @param {number} [itemsPerPage] item count to render per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyRateApi
     */
    public listCurrencyRate(page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig) {
        return CurrencyRateApiFp(this.configuration).listCurrencyRate(page, itemsPerPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Finds the CurrencyRate with the requested ID and returns it.
     * @summary Find a CurrencyRate by ID
     * @param {number} id ID of the CurrencyRate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyRateApi
     */
    public readCurrencyRate(id: number, options?: RawAxiosRequestConfig) {
        return CurrencyRateApiFp(this.configuration).readCurrencyRate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Find the attached Bank of the CurrencyRate with the given ID
     * @summary Find the attached Bank
     * @param {number} id ID of the CurrencyRate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyRateApi
     */
    public readCurrencyRateBank(id: number, options?: RawAxiosRequestConfig) {
        return CurrencyRateApiFp(this.configuration).readCurrencyRateBank(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates a CurrencyRate and persists changes to storage.
     * @summary Updates a CurrencyRate
     * @param {number} id ID of the CurrencyRate
     * @param {UpdateCurrencyRateRequest} updateCurrencyRateRequest CurrencyRate properties to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyRateApi
     */
    public updateCurrencyRate(id: number, updateCurrencyRateRequest: UpdateCurrencyRateRequest, options?: RawAxiosRequestConfig) {
        return CurrencyRateApiFp(this.configuration).updateCurrencyRate(id, updateCurrencyRateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

