/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateOfferRequest } from '../models';
// @ts-ignore
import type { ListBank400Response } from '../models';
// @ts-ignore
import type { OfferBankRead } from '../models';
// @ts-ignore
import type { OfferCreate } from '../models';
// @ts-ignore
import type { OfferList } from '../models';
// @ts-ignore
import type { OfferRead } from '../models';
// @ts-ignore
import type { OfferUpdate } from '../models';
// @ts-ignore
import type { UpdateOfferRequest } from '../models';
/**
 * OfferApi - axios parameter creator
 * @export
 */
export const OfferApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new Offer and persists it to storage.
         * @summary Create a new Offer
         * @param {CreateOfferRequest} createOfferRequest Offer to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOffer: async (createOfferRequest: CreateOfferRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createOfferRequest' is not null or undefined
            assertParamExists('createOffer', 'createOfferRequest', createOfferRequest)
            const localVarPath = `/offers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createOfferRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes the Offer with the requested ID.
         * @summary Deletes a Offer by ID
         * @param {number} id ID of the Offer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOffer: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteOffer', 'id', id)
            const localVarPath = `/offers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List Offers.
         * @summary List Offers
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOffer: async (page?: number, itemsPerPage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/offers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Finds the Offer with the requested ID and returns it.
         * @summary Find a Offer by ID
         * @param {number} id ID of the Offer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readOffer: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('readOffer', 'id', id)
            const localVarPath = `/offers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Find the attached Bank of the Offer with the given ID
         * @summary Find the attached Bank
         * @param {number} id ID of the Offer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readOfferBank: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('readOfferBank', 'id', id)
            const localVarPath = `/offers/{id}/bank`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a Offer and persists changes to storage.
         * @summary Updates a Offer
         * @param {number} id ID of the Offer
         * @param {UpdateOfferRequest} updateOfferRequest Offer properties to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOffer: async (id: number, updateOfferRequest: UpdateOfferRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateOffer', 'id', id)
            // verify required parameter 'updateOfferRequest' is not null or undefined
            assertParamExists('updateOffer', 'updateOfferRequest', updateOfferRequest)
            const localVarPath = `/offers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateOfferRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OfferApi - functional programming interface
 * @export
 */
export const OfferApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OfferApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new Offer and persists it to storage.
         * @summary Create a new Offer
         * @param {CreateOfferRequest} createOfferRequest Offer to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOffer(createOfferRequest: CreateOfferRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfferCreate>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOffer(createOfferRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OfferApi.createOffer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes the Offer with the requested ID.
         * @summary Deletes a Offer by ID
         * @param {number} id ID of the Offer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOffer(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOffer(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OfferApi.deleteOffer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List Offers.
         * @summary List Offers
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listOffer(page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OfferList>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listOffer(page, itemsPerPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OfferApi.listOffer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Finds the Offer with the requested ID and returns it.
         * @summary Find a Offer by ID
         * @param {number} id ID of the Offer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readOffer(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfferRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readOffer(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OfferApi.readOffer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Find the attached Bank of the Offer with the given ID
         * @summary Find the attached Bank
         * @param {number} id ID of the Offer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readOfferBank(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfferBankRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readOfferBank(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OfferApi.readOfferBank']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates a Offer and persists changes to storage.
         * @summary Updates a Offer
         * @param {number} id ID of the Offer
         * @param {UpdateOfferRequest} updateOfferRequest Offer properties to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOffer(id: number, updateOfferRequest: UpdateOfferRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfferUpdate>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOffer(id, updateOfferRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OfferApi.updateOffer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OfferApi - factory interface
 * @export
 */
export const OfferApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OfferApiFp(configuration)
    return {
        /**
         * Creates a new Offer and persists it to storage.
         * @summary Create a new Offer
         * @param {CreateOfferRequest} createOfferRequest Offer to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOffer(createOfferRequest: CreateOfferRequest, options?: RawAxiosRequestConfig): AxiosPromise<OfferCreate> {
            return localVarFp.createOffer(createOfferRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes the Offer with the requested ID.
         * @summary Deletes a Offer by ID
         * @param {number} id ID of the Offer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOffer(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteOffer(id, options).then((request) => request(axios, basePath));
        },
        /**
         * List Offers.
         * @summary List Offers
         * @param {number} [page] what page to render
         * @param {number} [itemsPerPage] item count to render per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOffer(page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<OfferList>> {
            return localVarFp.listOffer(page, itemsPerPage, options).then((request) => request(axios, basePath));
        },
        /**
         * Finds the Offer with the requested ID and returns it.
         * @summary Find a Offer by ID
         * @param {number} id ID of the Offer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readOffer(id: number, options?: RawAxiosRequestConfig): AxiosPromise<OfferRead> {
            return localVarFp.readOffer(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Find the attached Bank of the Offer with the given ID
         * @summary Find the attached Bank
         * @param {number} id ID of the Offer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readOfferBank(id: number, options?: RawAxiosRequestConfig): AxiosPromise<OfferBankRead> {
            return localVarFp.readOfferBank(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a Offer and persists changes to storage.
         * @summary Updates a Offer
         * @param {number} id ID of the Offer
         * @param {UpdateOfferRequest} updateOfferRequest Offer properties to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOffer(id: number, updateOfferRequest: UpdateOfferRequest, options?: RawAxiosRequestConfig): AxiosPromise<OfferUpdate> {
            return localVarFp.updateOffer(id, updateOfferRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OfferApi - object-oriented interface
 * @export
 * @class OfferApi
 * @extends {BaseAPI}
 */
export class OfferApi extends BaseAPI {
    /**
     * Creates a new Offer and persists it to storage.
     * @summary Create a new Offer
     * @param {CreateOfferRequest} createOfferRequest Offer to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfferApi
     */
    public createOffer(createOfferRequest: CreateOfferRequest, options?: RawAxiosRequestConfig) {
        return OfferApiFp(this.configuration).createOffer(createOfferRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes the Offer with the requested ID.
     * @summary Deletes a Offer by ID
     * @param {number} id ID of the Offer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfferApi
     */
    public deleteOffer(id: number, options?: RawAxiosRequestConfig) {
        return OfferApiFp(this.configuration).deleteOffer(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List Offers.
     * @summary List Offers
     * @param {number} [page] what page to render
     * @param {number} [itemsPerPage] item count to render per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfferApi
     */
    public listOffer(page?: number, itemsPerPage?: number, options?: RawAxiosRequestConfig) {
        return OfferApiFp(this.configuration).listOffer(page, itemsPerPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Finds the Offer with the requested ID and returns it.
     * @summary Find a Offer by ID
     * @param {number} id ID of the Offer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfferApi
     */
    public readOffer(id: number, options?: RawAxiosRequestConfig) {
        return OfferApiFp(this.configuration).readOffer(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Find the attached Bank of the Offer with the given ID
     * @summary Find the attached Bank
     * @param {number} id ID of the Offer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfferApi
     */
    public readOfferBank(id: number, options?: RawAxiosRequestConfig) {
        return OfferApiFp(this.configuration).readOfferBank(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates a Offer and persists changes to storage.
     * @summary Updates a Offer
     * @param {number} id ID of the Offer
     * @param {UpdateOfferRequest} updateOfferRequest Offer properties to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfferApi
     */
    public updateOffer(id: number, updateOfferRequest: UpdateOfferRequest, options?: RawAxiosRequestConfig) {
        return OfferApiFp(this.configuration).updateOffer(id, updateOfferRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

