/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BankOffersList
 */
export interface BankOffersList {
    /**
     * 
     * @type {number}
     * @memberof BankOffersList
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof BankOffersList
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof BankOffersList
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof BankOffersList
     */
    'link': string;
}

