/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BankUpdate
 */
export interface BankUpdate {
    /**
     * 
     * @type {number}
     * @memberof BankUpdate
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof BankUpdate
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof BankUpdate
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof BankUpdate
     */
    'website'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankUpdate
     */
    'logo_url'?: string;
}

