/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CurrencyRate } from './currency-rate';
// May contain unused imports in some cases
// @ts-ignore
import type { Offer } from './offer';

/**
 * 
 * @export
 * @interface Bank
 */
export interface Bank {
    /**
     * 
     * @type {number}
     * @memberof Bank
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'website'?: string;
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'logo_url'?: string;
    /**
     * 
     * @type {Array<CurrencyRate>}
     * @memberof Bank
     */
    'currency_rates'?: Array<CurrencyRate>;
    /**
     * 
     * @type {Array<Offer>}
     * @memberof Bank
     */
    'offers'?: Array<Offer>;
}

