/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateCurrencyRateRequest
 */
export interface CreateCurrencyRateRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCurrencyRateRequest
     */
    'currency': string;
    /**
     * 
     * @type {number}
     * @memberof CreateCurrencyRateRequest
     */
    'rate': number;
    /**
     * 
     * @type {number}
     * @memberof CreateCurrencyRateRequest
     */
    'bank': number;
}

