/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Bank } from './bank';

/**
 * 
 * @export
 * @interface CurrencyRate
 */
export interface CurrencyRate {
    /**
     * 
     * @type {number}
     * @memberof CurrencyRate
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CurrencyRate
     */
    'currency': string;
    /**
     * 
     * @type {number}
     * @memberof CurrencyRate
     */
    'rate': number;
    /**
     * 
     * @type {Bank}
     * @memberof CurrencyRate
     */
    'bank': Bank;
}

