/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ListBank400Response
 */
export interface ListBank400Response {
    /**
     * 
     * @type {number}
     * @memberof ListBank400Response
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ListBank400Response
     */
    'status': string;
    /**
     * 
     * @type {any}
     * @memberof ListBank400Response
     */
    'errors'?: any;
}

