/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Bank } from './bank';

/**
 * 
 * @export
 * @interface Offer
 */
export interface Offer {
    /**
     * 
     * @type {number}
     * @memberof Offer
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    'link': string;
    /**
     * 
     * @type {Bank}
     * @memberof Offer
     */
    'bank': Bank;
}

