/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateOfferRequest
 */
export interface UpdateOfferRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateOfferRequest
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOfferRequest
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOfferRequest
     */
    'link'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateOfferRequest
     */
    'bank'?: number;
}

