/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * API для справочника банков
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateBankRequest
 */
export interface UpdateBankRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateBankRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBankRequest
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBankRequest
     */
    'website'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBankRequest
     */
    'logo_url'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateBankRequest
     */
    'currency_rates'?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateBankRequest
     */
    'offers'?: Array<number>;
}

