/* tslint:disable */
/* eslint-disable */
/**
 * Bank Directory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Bank
 */
export interface Bank {
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'website'?: string;
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'logoUrl'?: string;
    /**
     * 
     * @type {Array<CurrencyRate>}
     * @memberof Bank
     */
    'currencyRates'?: Array<CurrencyRate>;
    /**
     * 
     * @type {Array<Offer>}
     * @memberof Bank
     */
    'offers'?: Array<Offer>;
    /**
     * 
     * @type {string}
     * @memberof Bank
     */
    'updatedAt'?: string;
}
/**
 * Коды валют в формате ISO 4217
 * @export
 * @enum {string}
 */

export const CurrencyCode = {
    Usd: 'USD',
    Eur: 'EUR',
    Gbp: 'GBP',
    Jpy: 'JPY',
    Chf: 'CHF',
    Cad: 'CAD',
    Aud: 'AUD',
    Cny: 'CNY',
    Rub: 'RUB',
    Uah: 'UAH'
} as const;

export type CurrencyCode = typeof CurrencyCode[keyof typeof CurrencyCode];


/**
 * 
 * @export
 * @interface CurrencyRate
 */
export interface CurrencyRate {
    /**
     * 
     * @type {CurrencyCode}
     * @memberof CurrencyRate
     */
    'currency'?: CurrencyCode;
    /**
     * 
     * @type {number}
     * @memberof CurrencyRate
     */
    'rate'?: number;
}


/**
 * 
 * @export
 * @interface Offer
 */
export interface Offer {
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    'link'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Получить список банков
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        banksGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/banks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить банк по ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        banksIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('banksIdGet', 'id', id)
            const localVarPath = `/banks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Получить список банков
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async banksGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Bank>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.banksGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.banksGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить банк по ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async banksIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bank>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.banksIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.banksIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Получить список банков
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        banksGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Bank>> {
            return localVarFp.banksGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить банк по ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        banksIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Bank> {
            return localVarFp.banksIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Получить список банков
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public banksGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).banksGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить банк по ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public banksIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).banksIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}



